import Providers from './providers/Providers'
import { Box, CssBaseline } from '@mui/material'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="uk">
            <body>
                <CssBaseline />
                <Providers>
                    <Box
                        sx={{
                            display: 'flex',
                            flexDirection: 'column',
                            minHeight: '100vh',
                            minWidth: '100%',
                        }}
                    >
                        {children}
                    </Box>
                </Providers>
            </body>
        </html>
    )
}
